# -*- coding: utf-8 -*-
"""白蛾3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmtvyaKD9Uj4SKpBFQqvhiK6FqXfW_d_
"""

import streamlit as st
import random
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

# 設定網頁標題
st.set_page_config(page_title="胡椒蛾演化模擬", layout="wide") # 使用寬版佈局
st.title("🦋 胡椒蛾演化模擬器")

# 1. 初始化數值
if 'white' not in st.session_state:
    st.session_state.white = 8
    st.session_state.black = 2
    st.session_state.history = pd.DataFrame({'Step': [0], 'White': [8], 'Black': [2]})

# 2. 邏輯函式
def emit_smoke():
    if st.session_state.white > 1:
        change = random.randint(1, 2)
        if st.session_state.white - change < 1:
            change = st.session_state.white - 1
        st.session_state.white -= change
        st.session_state.black += change
        
        # 紀錄歷史
        new_data = pd.DataFrame({
            'Step': [len(st.session_state.history)],
            'White': [st.session_state.white],
            'Black': [st.session_state.black]
        })
        st.session_state.history = pd.concat([st.session_state.history, new_data], ignore_index=True)

# 3. 版面配置：左邊是大圖，右邊是小數據
col_main, col_side = st.columns([2.5, 1]) # 比例設為 2.5 : 1，讓主圖變大

with col_main:
    st.write("### 🏭 生態觀察窗 (點擊下方按鈕觸發)")
    fig_sim, ax_sim = plt.subplots(figsize=(10, 6.5)) # 增大主圖比例
    ax_sim.set_xlim(0, 100)
    ax_sim.set_ylim(0, 70)
    ax_sim.set_axis_off()
    
    try:
        img_f = mpimg.imread('工廠圖片.jpg')
        img_w = mpimg.imread('白蛾.jpg')
        img_b = mpimg.imread('黑蛾.jpg')
        ax_sim.imshow(img_f, extent=[0, 100, 0, 70], aspect='auto', alpha=0.6)
        
        for _ in range(st.session_state.white):
            rx, ry = random.randint(5, 85), random.randint(5, 55)
            ax_sim.imshow(img_w, extent=[rx, rx+12, ry, ry+9], zorder=3)
        for _ in range(st.session_state.black):
            rx, ry = random.randint(5, 85), random.randint(5, 55)
            ax_sim.imshow(img_b, extent=[rx, rx+12, ry, ry+9], zorder=3)
        st.pyplot(fig_sim)
    except:
        st.error("載入圖片時出錯。")

with col_side:
    st.write("### 📈 數據趨勢")
    # 縮小折線圖的尺寸
    fig_chart, ax_chart = plt.subplots(figsize=(4, 4)) 
    ax_chart.plot(st.session_state.history['Step'], st.session_state.history['White'], 
                  marker='o', markersize=4, label='White', color='#cccccc')
    ax_chart.plot(st.session_state.history['Step'], st.session_state.history['Black'], 
                  marker='o', markersize=4, label='Black', color='#333333')
    ax_chart.set_title("Population Change", fontsize=10)
    ax_chart.tick_params(labelsize=8)
    ax_chart.legend(prop={'size': 8})
    st.pyplot(fig_chart)
    
    # 放置按鈕在側邊欄下方，更符合操作邏輯
    if st.button("🏭 排放黑煙", use_container_width=True):
        emit_smoke()
        st.rerun()
    
    if st.button("🔄 重置模擬", use_container_width=True):
        st.session_state.white, st.session_state.black = 8, 2
        st.session_state.history = pd.DataFrame({'Step': [0], 'White': [8], 'Black': [2]})
        st.rerun()

st.caption("這是一個模擬天擇過程的互動工具。隨著環境變黑，白蛾的存活率下降。")
