# -*- coding: utf-8 -*-
"""白蛾3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmtvyaKD9Uj4SKpBFQqvhiK6FqXfW_d_
"""

import streamlit as st
import random
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# 設定網頁標題
st.set_page_config(page_title="胡椒蛾演化模擬器", layout="centered")
st.title("🦋 胡椒蛾工業黑化模擬")

# 1. 初始化數值 (儲存在 session_state 確保重新整理時資料不消失)
if 'white' not in st.session_state:
    st.session_state.white = 8
    st.session_state.black = 2

# 2. 側邊欄控制與統計
with st.sidebar:
    st.header("數據統計")
    st.metric("白蛾數量", st.session_state.white)
    st.metric("黑蛾數量", st.session_state.black)
    if st.button("重設模擬"):
        st.session_state.white = 8
        st.session_state.black = 2
        st.rerun()

# 3. 點擊邏輯函式
def emit_smoke():
    if st.session_state.white > 1:
        change = random.randint(1, 2)
        if st.session_state.white - change < 1:
            change = st.session_state.white - 1
        st.session_state.white -= change
        st.session_state.black += change
    else:
        st.warning("演化已達平衡，白蛾剩餘 1 隻。")

# 4. 繪製模擬畫面
fig, ax = plt.subplots(figsize=(10, 6))
img_factory = mpimg.imread('工廠圖片.jpg')
img_white = mpimg.imread('白蛾.jpg')
img_black = mpimg.imread('黑蛾.jpg')

ax.imshow(img_factory, extent=[0, 100, 0, 70], aspect='auto', alpha=0.6)
ax.set_axis_off()

# 隨機放置蛾群
for _ in range(st.session_state.white):
    rx, ry = random.randint(5, 85), random.randint(5, 55)
    ax.imshow(img_white, extent=[rx, rx+12, ry, ry+9])
for _ in range(st.session_state.black):
    rx, ry = random.randint(5, 85), random.randint(5, 55)
    ax.imshow(img_black, extent=[rx, rx+12, ry, ry+9])

# 顯示圖片
st.pyplot(fig)

# 5. 人性化互動：大按鈕
if st.button("🏭 點擊工廠排放黑煙", use_container_width=True):
    emit_smoke()
    st.rerun()

st.info("這是一個模擬 19 世紀英國工業革命時期，環境汙染如何透過天擇改變蛾群顏色的教學工具。")